spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost/universidad?createDatabaseIfNotExist=true
    username : root
    password: tolbar12345
server:
  port: 8282