version: '3.1'
services:
  mysql:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tolbar12345
    ports:
      - 3306:3306